import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Reviews from '../module/reviews/Reviews'
import Project from "../module/project/Project"
import Login from '../module/login/Login'
import Forgot from '../module/login/Forgot'
import Reset from '../module/login/Reset'
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="wrapper">
      <Head>
        <title>Alpha Research Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
      </Head>
      {/* <Project /> */}
      {/* <Reviews /> */}
      <Login />
      {/* <Forgot /> */}
      {/* <Reset /> */}
    </div>
  )
}

export default Home
