import React, { Fragment } from 'react'
import Reviews from '../module/reviews/Reviews'

const termsAndConditions = () => {
  return (
    <Fragment>
      <div className="rt-termsholder container">
        <p className="c13"><span className="c4 c6">Alpha Research Tools Terms and Conditions</span></p>
        <p className="c1"><span className="c0">Last Update:</span><span className="c2">&nbsp;July 25, 2022</span></p>
        <p className="c1">These Terms and Conditions ("<span className="c0">Terms</span>") govern your ("<span className="c0">User</span>" or “<span className="c0">you”</span> or ‘‘<span className="c0">your’’</span>) use of the alpharesearch.tools website (referred to collectively as the "<span className="c0">Service</span>") operated by ("<span className="c0">Alpha Research Tools</span>", "<span className="c0">us</span>", "<span className="c0">we</span>", or "<span className="c0">our</span>").</p>
        <p className='c1'><span className='c0'>Acceptance of Terms</span></p>
        <p className='c1'>By accessing, using, visiting, or browsing the Platform or the Service you accept and agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, do not use our Service and Platform.</p>
        <p className='c1'><span className='c0'>Platform</span></p>
        <p className='c1'>Alpha Research Tools is a platform where you can discover new non-fungible token projects, view their details, add them to your watchlist and view their growth.</p>
        <p className='c1'><span className='c0'>Account</span></p>
        <p className='c1'>In order to access certain features of the Service, you must create an account by signing in with one of the given methods on your profile page.</p>
        <p className='c1'>When you create an account with us, you guarantee that you are above the age of 18, and that the information you provide us is accurate, correct and up to date. Inaccurate, incorrect, or obsolete information may result in the immediate termination of your account on the Service.</p>
        <p className='c1'>You are responsible for maintaining the confidentiality of your account. You agree to be fully responsible for any activity that occur through your account. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
        <p className='c1'>Alpha Research Tools may require you to provide additional information and documents at the request of any authorized public institution and organization or in case of application of any applicable law or regulation. Alpha Research Tools, at its sole discretion, may pause or cancel your account in relation to this matter.</p>
        <p className='c1'><span className='c0'>Platform Rules</span></p>
        <p className='c1'>You agree, warrant, represent and acknowledge that you will abide by these Terms, you are solely responsible for your activities and you will not:</p>
        <ul className="c8 lst-kix_list_1-0 start">
          <li className="c3 li-bullet-0">violate any law, regulation, statute, intellectual property or other third party right or contract;</li>
          <li className="c3 li-bullet-0">provide false or misleading information;</li>
          <li className="c3 li-bullet-0">use the Service in any manner that could interfere with, damage, negatively affect, disable, overburden or impair the functioning of the Service in any manner;</li>
          <li className="c3 li-bullet-0">jeopardize the security of any account in any way;</li>
          <li className="c3 li-bullet-0">restrict or inhibit any other person from using the Service;</li>
          <li className="c3 li-bullet-0">act in a way that is harmful, threatening, abusive, harassing, degrading, hateful or intimidating, or otherwise fail to respect the rights and dignity of others;</li>
          <li className="c3 li-bullet-0">copy, store, reproduce, modify, adapt, translate, create derivative works of, sell, rent, lease, loan, distribute or otherwise exploit any portion of the Service or the content therein;</li>
          <li className="c3 li-bullet-0">disseminate any software or interact with any API in any manner;</li>
          <li className="c3 li-bullet-0">decompile or reverse engineer any aspect of the Service or attempt to obtain the source code;</li>
          <li className="c3 li-bullet-0">violate the security of any computer network;</li>
          <li className="c3 li-bullet-0">process personal data collected from our Service in a manner that does not fully ensure compliance with data protection regulations;</li>
        </ul>
        <p className='c1'>Alpha Research Tools reserves the right (but does not have the obligation) to remove any content from the Service at any time, for any reason. You remain solely responsible for all content that you create, share, upload, post, send or store through the Service.</p>
        <p className='c1'><span className='c0'>Alpha Research Tools’s Own NFTs</span></p>
        <p className='c1'>Alpha Research Tools may release, from time to time, a unique Ethereum blockchain-tracked, non-fungible token (‘‘<span className='c0'>Alpha Research Tools NFT</span>’’) by minting the original artwork (‘‘<span className='c0'>Artwork</span>’’).</p>
        <p className='c1'>Alpha Research Tools, at its sole discretion, may grant the right to purchase Alpha Research Tools NFT to a selected audience. Prices of such Alpha Research Tools NFT will be determined by Alpha Research Tools.</p>
        <p className='c1'>You may purchase Alpha Research Tools NFT originally from Alpha Research Tools or on a marketplace from a legitimate owner. (‘‘<span className='c0'>Alpha Research Tools NFT Owner</span>’’)</p>
        <p className='c1'>Subject to compliance with the terms of this Agreement, Alpha Research Tools hereby grants Alpha Research Tools NFT Owners, a worldwide, non-exclusive, personal, limited license to display the Alpha Research Tools NFT and Artwork, solely with respect to the Alpha Research Tools NFT that you own, including on social media platforms, digital galleries, marketplaces or otherwise, in association with your offer to sell or trade your Alpha Research Tools NFT or other legitimate motives. This license does not grant you any rights regarding the Artwork separate from the associated NFT. You acknowledge and agree that Alpha Research Tools owns all legal rights including all copyrights, title and interest regarding the Artwork.</p>
        <p className='c1'>The license granted herein applies only to the extent that you continue to own the Alpha Research Tools NFT. If at any time you sell, trade, donate, give away, or transfer your Alpha Research Tools NFT, the license granted herein shall be transferred with the Alpha Research Tools NFT, to the new owner, and you will have no further rights regarding Alpha Research Tools NFT or the Artwork associated with that Alpha Research Tools NFT.</p>
        <p className='c1'><span className='c0'>Violations</span></p>
        <p className='c1'>Alpha Research Tools NFT Owner agrees not to, or will not permit any third party to:</p>
        <ul className="c8 lst-kix_list_1-0 start">
          <li className="c3 li-bullet-0">modify the Artwork associated with your Alpha Research Tools NFT in any way;</li>
          <li className="c3 li-bullet-0">use the Artwork separate from the associated NFT to advertise, market, or sell any product or service;</li>
          <li className="c3 li-bullet-0">use the Alpha Research Tools NFT or Artwork in a way that is harmful, threatening, abusive, harassing, degrading, hateful, malicious, offensive or otherwise violating any right or applicable law or regulation;</li>
          <li className="c3 li-bullet-0">act with ill will to decrease the value of Alpha Research Tools NFT;</li>
          <li className="c3 li-bullet-0">intentionally attempt to harm Alpha Research Tools in any way;</li>
          <li className="c3 li-bullet-0">attempt to mint, tokenize, or create a digital token representing the Artwork on any platform;</li>
          <li className="c3 li-bullet-0">falsify, misrepresent, or conceal the authorship of the Artwork or the Alpha Research Tools NFT;</li>
          <li className="c3 li-bullet-0">make copies or derivative works embodying the Artwork or Alpha Research Tools NFT.</li>
        </ul>
        <p className='c1'>You are responsible for verifying the identity of third party platforms that sell NFTs by using our name.</p>
        <p className='c1'>Refund requests may be considered by Alpha Research Tools on a case-by-case basis and granted in sole discretion of Alpha Research Tools.</p>
        <p className='c1'>You will be responsible for withholding, filing, and reporting all taxes and other governmental duties associated with your activity in connection with the Alpha Research Tools NFT and other Services.</p>
        <p className='c1'><span className='c0'>Electronic Communications</span></p>
        <p className='c1'>We may provide you with electronic communications relating to the Service and your account (e.g. confirmation messages, notices, new features and product updates) in electronic form only, for example via emails to your email address if provided by you.</p>
        <p className='c1'>When you share your electronic address with us, we have a legitimate interest in providing you with direct marketing communications (e.g. discounts, promotions, offers, newsletters). You may always unsubscribe from our direct marketing communications by clicking on the "unsubscribe" link located on the bottom of our e-mails. This does not opt you out of receiving Service-related electronic communications.</p>
        <p className='c1'><span className='c0'>Intellectual Property</span></p>
        <p className='c1'>Without prejudice to the provisions about Alpha Research Tools NFT, you hereby agree that Alpha Research Tools owns all intellectual property rights in the Service. All present and future rights to intellectual property including but not limited to inventions, discoveries, trade secrets, secret processes, know-hows, concepts, ideas, information, processes, data, formulas, improvements, work products developed in whole or in part by Alpha Research Tools, trademarks (whether registered or not), patents, designs, copyright, and corresponding property rights under the laws of any jurisdiction belong to Alpha Research Tools. We will own exclusive rights to any feedback, suggestions, ideas, or other information or materials that you provide regarding Alpha Research Tools.</p>
        <p className='c1'>Without prejudice to the provisions about Alpha Research Tools NFT; the Service and its original content, features and functionality are and will remain the exclusive property of Alpha Research Tools and its licensors. You agree that you will not reproduce, duplicate, copy, sell, trade or resell the Service for any purpose. You must not obscure, alter, remove or delete any copyright or other proprietary notices contained in the Service. You will not copy, modify, adapt, translate or otherwise create derivative works of the Service. You warrant that you will not attempt or assist others to attempt or actually reverse engineer, decompile, disassemble or otherwise attempt to discover the source code of the software. You agree to comply with all applicable laws and regulations in your use of and access to the Service.</p>
        <p className='c1'><span className='c0'>Privacy</span></p>
        <p className='c1'>We value your policy and are committed to comply with the EU General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA). For more information, please see our Privacy Policy on our Platform.</p>
        <p className='c1'>You hereby warrant and undertake to comply with the data protection regulations. You agree that you will responsibly use, transfer, and process the personal data you received from Alpha Research Tools. You hereby confirm that you independently determine the purposes and means of the processing of personal data, act as an independent controller and will take all necessary measures.</p>
        <p className='c1'>Direct notification of individuals you are friends with or follow (‘‘<span className='c0'>Social Media Platform or Marketplace Users</span>'’) by Alpha Research Tools would involve a disproportionate effort (where processing is carried out for statistical purposes) under Art. 14. paragraph 5 (b) GDPR. Therefore, we are not obliged to notify them. You hereby agree to take all necessary actions to notify them. Also, there is a notification in our Privacy Policy.</p>
        <p className='c1'>If any requests information about the User who collected his/her personal data, Alpha Research Tools must disclose your information to the relevant Social Media Platform or Marketplace User to act in accordance with the data protection regulations.</p>
        <p className='c1'>You are prohibited from using the personal data collected from our Service after Alpha Research Tools or data subject request to remove it, if you do not have any further legitimate basis for processing such personal data. Such personal data must be deleted within 72 hours following the notification. In that case you are also required to ensure any third party to whom you transfer such personal data to delete such information as well.</p>
        <p className='c1'><span className='c0'>Third Party Materials</span></p>
        <p className='c1'>Our Service may display, include, or make available third-party content that Alpha Research Tools has no control over or may contain links to third party web sites or services that are not owned or controlled by Alpha Research Tools. You acknowledge and agree that Alpha Research Tools is not responsible for third party materials, links and information, including their accuracy, completeness, reliability, validity, copyright compliance, legality, decency, quality, or any other aspect thereof.</p>
        <p className='c1'>These Terms will continue to apply to you until terminated by either you or Alpha Research Tools. However, you acknowledge and agree that the provisions about Privacy, Intellectual Property, Disclaimer of Warranties, Indemnification, and Limitation of Liability are irrevocable and will therefore continue after termination of these Terms.</p>
        <p className='c1'>Alpha Research Tools may terminate these Terms or suspend your access to the Service or your account at any time, without prior notice or liability, for any reason including but not limited to the breach of these Terms.</p>
        <p className='c1'>You may terminate these Terms at any time by contacting us via support@alpharesearch.tools.</p>
        <p className='c1'>If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms and our Privacy Policy constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have had between us regarding the Service.</p>
        <p className='c1'>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.</p>
        <p className='c1'><span className='c0'>Indemnification</span></p>
        <p className='c1'>You agree to defend, indemnify and hold harmless Alpha Research Tools and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of (1) your breach of these Terms; (2) any content you shared or transferred; (3) any activity in which you engage on or through your account; and (4) your violation of any law or the rights of a third party.</p>
        <p className='c1'><span className='c0'>Limitation of Liability</span></p>
        <p className='c1'>In no event shall Alpha Research Tools, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>
        <p className='c1'><span className='c0'>Disclaimer of Warranties</span></p>
        <p className='c1'><em>ALPHA RESEARCH TOOLS WILL REASONABLY ENDEAVOUR TO ENSURE THAT THE SERVICE IS AVAILABLE AND ACCESSIBLE, HOWEVER, ALPHA RESEARCH TOOLS DOES NOT GIVE ANY GUARANTEE OR ASSURANCE THAT THE SERVICE WILL ALWAYS BE AVAILABLE, ACCESSIBLE, CORRECT OR UP TO DATE. SERVICE IS OFFERED WITHOUT ANY KIND OF WARRANTY, ON AN "AS IS" AND "AS AVAILABLE" BASIS. ALPHA RESEARCH TOOLS IS NOT OBLIGATED TO ENSURE THAT THE SERVICE CAN BE ACCESSED AT ALL TIMES WITHOUT ANY INTERRUPTIONS, FAULTS OR MALFUNCTIONS.</em></p>
        <p className='c1'><em>ALPHA RESEARCH TOOLS WILL REASONABLY ENDEAVOUR TO ENSURE THAT THE SERVICE IS AVAILABLE AND ACCESSIBLE, HOWEVER, ALPHA RESEARCH TOOLS DOES NOT GIVE ANY GUARANTEE OR ASSURANCE THAT THE SERVICE WILL ALWAYS BE AVAILABLE, ACCESSIBLE, CORRECT OR UP TO DATE. SERVICE IS OFFERED WITHOUT ANY KIND OF WARRANTY, ON AN "AS IS" AND "AS AVAILABLE" BASIS. ALPHA RESEARCH TOOLS IS NOT OBLIGATED TO ENSURE THAT THE SERVICE CAN BE ACCESSED AT ALL TIMES WITHOUT ANY INTERRUPTIONS, FAULTS OR MALFUNCTIONS.</em></p>
        <p className='c1'><em>ALPHA RESEARCH TOOLS DOES NOT WARRANT OR GUARANTEE THAT THE PLATFORM WILL MEET ALL THE REQUIREMENTS OF USERS; BE NONSTOP, UP-TO-DATE, CURRENT, SECURE AND ERROR-FREE; AND ALSO, DOES NOT WARRANT OR GUARANTEE THAT THE RESULTS OBTAINED BY USING THE SERVICE WILL BE ACCURATE OR RELIABLE OR THE DEFECTS WILL BE CORRECTED.</em></p>
        <p className='c1'><em>YOU ACKNOWLEDGE THAT THE USE OF THE SERVICE IS PROVIDED OVER THE INTERNET AND MOBILE NETWORKS, THEREFORE THE AVAILABILITY AND QUALITY OF THE SERVICE MAY BE AFFECTED BY FACTORS OUTSIDE OF THE ACCEPTABLE CONTROL OF ALPHA RESEARCH TOOLS.</em></p>
        <p className='c1'><em>ALPHA RESEARCH TOOLS SHALL ENDEAVOUR TO ENSURE THE ACCURACY OF THE INFORMATION IN THE PLATFORM, HOWEVER ALPHA RESEARCH TOOLS SHALL NOT BE RESPONSIBLE FOR INCOMPLETE, MISSING, WRONG OR INCORRECT INFORMATION.</em></p>
        <p className='c1'><em>YOU ACKNOWLEDGE THAT THE PERFORMANCE OF THE SERVICE IS DIRECTLY LINKED TO THE PERFORMANCE OF THIRD-PARTY SERVICES. ALPHA RESEARCH TOOLS DISCLAIMS ALL RESPONSIBILITY OF FAILURES IN THE PERFORMANCE OF THE SERVICE, CAUSED BY NONPERFORMANCE OF THIRD-PARTY SERVICES. SINCE ALPHA RESEARCH TOOLS PROVIDES ITS SERVICE THROUGH THIRD-PARTY, ANY TECHNICAL ISSUE CAUSED BY IT MAY AFFECT THE SERVICE. ALPHA RESEARCH TOOLS DOES NOT BEAR ANY LIABILITY REGARDING SUCH MATTER.</em></p>
        <p className='c1'><em>YOU ACKNOWLEDGE THAT NO CONTENT ON THE SERVICE IS DESIGNED FOR THE SPECIFIC NEEDS OF ANY INDIVIDUALS, ORGANIZATION, ENTITY OR GROUP OF INDIVIDUALS.</em></p>
        <p className='c1'><em>YOU MAY USE THE DATA/CONTENT COLLECTED AND DISPLAYED SOLELY FOR INFORMATIONAL PURPOSES. YOU UNDERSTAND AND ACKNOWLEDGE THAT SUCH DATA/CONTENT MAY NOT BE EXHAUSTIVE AND THE ANALYSIS OF THE DATA/CONTENT IS BASED ON WHAT THIRD-PARTY DATA SOURCES PROVIDE TO ALPHA RESEARCH TOOLS. THE DATA/CONTENT IS BASED ON PUBLICLY AVAILABLE DATA/CONTENT AND ALPHA RESEARCH TOOLS DOES NOT VERIFY THE ACCURACY OF DATA/CONTENT PROVIDED BY SUCH THIRD PARTIES. ANY USE OF THE DATA/CONTENT EXCEPT AS SPECIFICALLY DESCRIBED HEREIN IS AT YOUR OWN RISK.</em></p>
        <p className='c1'><span className='c0'>Force Majeure</span></p>
        <p className='c1'>Alpha Research Tools shall not be liable for any failure or delay in the performance of its obligations occurring by reason of circumstances beyond its control, including but not limited to strikes, work stoppages, accidents, fires, explosions, acts of war or terrorism, civil or military disturbances, embargoes, epidemic, nuclear or natural catastrophes or acts of God, and interruptions, loss or malfunctions of utilities, power supply, communications, or computer (software and hardware) services.</p>
        <p className='c1'><span className='c0'>Governing Law</span></p>
        <p className='c1'>These Terms shall be governed and construed in accordance with the laws of Curaçao, without regard to its conflict of law provisions.</p>
        <p className='c1'><span className='c0'>Changes</span></p>
        <p className='c1'>We reserve the right to revise, amend or otherwise change these Terms without prior notice to you. You acknowledge and agree that it is your responsibility to review these Terms periodically for changes. You waive any right you may have to receive a notice of such changes. Your continued use of the Service after the effective date of such change will constitute your consent to the revised, amended, or otherwise changed Terms. If you do not agree to the changes, you must stop using the Service.</p>
        <p className='c1'><span className='c0'>Contact Us</span></p>
        <p className='c1'>If you have any questions about these Terms, please contact us via support@alpharesearch.tools.</p>
      </div>
    </Fragment>
  )
}

export default termsAndConditions